AllCops:
  Includes:
    - Rakefile
    - config.ru
  Excludes:
    - vendor/**

Encoding:
  Enabled: false

HashSyntax:
  Enabled: false

IfUnlessModifier:
  Enabled: false

LineLength:
  Enabled: true
  Max: 90
